### ISSUE TITLE
Clicking on the + button in animation freeze the unity editor

### ISSUE THREAD

**Issue by mmar58** [Cryoscopic-E/PDSim#7]
![image](https://github.com/Cryoscopic-E/PDSim/assets/81753445/fd658215-c3b2-48e5-9132-c2cd3e2ec932)
![image](https://github.com/Cryoscopic-E/PDSim/assets/81753445/8491ccda-fecd-4354-b1f4-05361152002e)

I am trying to run your pdSim in Unity 2022.3.13. The backend is running and I have created a new scene with your pdsim menu. When I run it gets connected but can't see any model and when I click on the plus button in animation(right side option in the image), it freezes the unity editor.

So if you can fix the problems or guide me. It will be very helpful

**Comment by Cryoscopic-E** [comment]
Hi, PDSim has been tested on Unity 2022.3.x LTS, I suggest you try that. The models are missing because you can customize the appearance of the types, if you click on "Problem Objects", the inspector will show the possible types to customise (in this case will be 'block'). If you want to run a premade demo I suggest you check out the 'demos' branch.

**Comment by mmar58** [comment]
Hi, thanks. in the demo scenes, I can run and see the demos. and sorry for the mistake, I am testing your project in unity 2022.3.13.
But clicking on the plus icon in the animation list to add animation still freezes the unity editor. Please fix it.

**Comment by Cryoscopic-E** [comment]
Could you provide additional feedback about the freezing? when it happens or have you just converted the previous 2023 version of the project to 2022? Cheers!

**Comment by mmar58** [comment]
No, my Unity version was always 2022, I just made a mistake and wrote 2023. Sorry for that.
So I opened the demo scene, I can play it and it plays awesome.
**Problem Steps**
But in demo scenes or created scenes using pdSim, First click on animations in the hierarchy. Then click on + icon of any animation method to add the animation. Whenever I click on the + icon, the unity just freezes.

**Comment by Cryoscopic-E** [comment]
OK, may I ask what OS you are using? Apologies for all the questions but I don't experience the problem and I'm not able to reproduce it :)

**Comment by mmar58** [comment]
Oh, I checked again. Sorry, it was my mistake. Whenever I clicked on the + icon it opened the create animation windows, but the window was in the middle of my multi-monitor, so I couldn't detect it. Thanks for your time and sorry.
