### ISSUE TITLE
Files from Paper

### ISSUE THREAD

**Issue by sazirarrwth99** [Cryoscopic-E/PDSim#9]
Hi,

thanks for this work. Is there any chance to get the Unityfiles from the Papers (e.g. blocksworld). It could open up new use cases. 

Thanks
Best

**Comment by Cryoscopic-E** [comment]
Hi! thanks for your interest!

Yes, you can now with this new update.

If you check the new README you'll find instructions on how to setup PDSim as a Unity package and import the samples from there.

Let me know if this solves your problem!

**Comment by sazirarrwth99** [comment]
Amazing, thanks!
